openapi: 3.0.0
info:
  title: User Management API
  version: '1.0'
  description: API for managing users with profile images
servers:
  - url: http://localhost:8000/api
    description: Local development server
paths:
  /users:
    get:
      summary: Get list of users
      responses:
        '200':
          description: List of users
    post:
      summary: Create a new user
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                phone:
                  type: string
                profile_image:
                  type: string
                  format: binary
      responses:
        '201':
          description: User created successfully